export const FLOWER_WORD = {
  F: [
    'Flower',
    'Fascinating',
    'Fabulous',
    'Funny',
    'Fresh',
    'Fairness',
    'Faithful',
    'Fanciful',
    'Fantasy',
    'Forgiving',
    'Fulfilling',
  ],
  L: [
    'Loyal',
    'Lovable',
    'Lifesaver',
    'Light',
    'Legendary',
    'Leinent',
    'Likable',
    'Listener',
    'Luminous',
    'Luscious',
  ],
  O: [
    'Onwarding',
    'Openhearted',
    'Openminded',
    'Outstanding',
    'Outsmart',
    'Oomph',
    'Outperforming',
    'Observant',
    'Ongoing',
    'Optimistic',
    'Overjoying',
    'Overflowing',
  ],
  R: [
    'Real A$$ NIGGA',
    'Radiance',
    'Reasonable',
    'Receptive',
    'Reflective',
    'Resilent',
    'Resourceful',
    'Righteous',
    'Relaxed',
    'Refreshing',
    'Rectify',
  ],
}
